### ISSUE TITLE
Memory issue in Darcy-object

### ISSUE THREAD

**Issue by Maren425** [OPM/IFEM-Darcy#51]
It seems like the Darcy-object remembers something from the last run, which affects the outcome of the next run. 
If I run the following code 
![image](https://user-images.githubusercontent.com/60742725/175939667-9c94ae0e-fdf3-4af0-9ab9-fdddbd1c10d0.png)
I get the following plot
![image](https://user-images.githubusercontent.com/60742725/175940076-a0dbf46d-1c05-4d97-b7dd-4f112a8273f7.png)
and if I change p1 from `p1=np.linspace(0, 4, 10)` to `p1=np.linspace(-4, 4, 10)` the plot becomes
![image](https://user-images.githubusercontent.com/60742725/175940673-4a79ce5c-1145-4863-b078-ffa01042d2df.png)
i.e. the QoI values do not change, even though the pressure values are changed. 
However if I run the following code, where I make a new Darcy-object for each loop
![image](https://user-images.githubusercontent.com/60742725/175941430-61f20965-253e-4270-887e-9da40d4323ff.png)
I get the following plot 
![image](https://user-images.githubusercontent.com/60742725/175941481-f6792739-b79a-423c-ad9a-2a24ba4a1810.png)
If I again change p1 from `p1=np.linspace(0, 4, 10)` to `p1=np.linspace(-4, 4, 10)` the plot becomes
![image](https://user-images.githubusercontent.com/60742725/175941609-52521dd6-918e-4fa9-b61c-a8681ef26e55.png)
Here we can see that the two plots agree in the area where the pressure is equal (i.e. p $\in$ [0,4]).

The XML-file used:
![image](https://user-images.githubusercontent.com/60742725/175943729-e42d6144-d109-4444-b236-c851fb85a685.png)

Code used to make geometry:
![image](https://user-images.githubusercontent.com/60742725/175943912-b8e4d6f0-11f8-4b61-a98a-c79b7de92279.png)

**Comment by akva2** [comment]
thanks for the report. i have taken care of the problem (it was a core ifem fix so only the referred pr is necessary). if a reproducible case for the reported memory leak is presented i can look into that as well.
